// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxlzgcaldsdydytxundk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4bHpnY2FsZHNkeWR5dHh1bmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODIzMDQsImV4cCI6MjA2MDU1ODMwNH0.lg-lBWl_2B0UicKOCqx5dcIN3zeQyNv2dmaMICeMYrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);